// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'new_linux'.
TEST_SECTION("new_linux", "sock_flags_kern.o", "cgroup/sock1")
TEST_SECTION("new_linux", "sock_flags_kern.o", "cgroup/sock2")
TEST_SECTION("new_linux", "sockex1_kern.o", "socket1")
TEST_SECTION("new_linux", "sockex2_kern.o", "socket2")
TEST_SECTION("new_linux", "sockex3_kern.o", "socket/0")
TEST_SECTION("new_linux", "sockex3_kern.o", "socket/1")
TEST_SECTION("new_linux", "sockex3_kern.o", "socket/2")
TEST_SECTION("new_linux", "sockex3_kern.o", "socket/3")
TEST_SECTION("new_linux", "sockex3_kern.o", "socket/4")
TEST_SECTION("new_linux", "trace_output_kern.o", "kprobe/__x64_sys_write")
TEST_SECTION("new_linux", "tracex1_kern.o", "kprobe/__netif_receive_skb_core")
TEST_SECTION("new_linux", "tracex2_kern.o", "kprobe/__x64_sys_write")
TEST_SECTION("new_linux", "tracex2_kern.o", "kprobe/kfree_skb")
TEST_SECTION("new_linux", "tracex3_kern.o", "kprobe/blk_account_io_done")
TEST_SECTION("new_linux", "tracex3_kern.o", "kprobe/blk_mq_start_request")
TEST_SECTION("new_linux", "tracex4_kern.o", "kprobe/kmem_cache_free")
TEST_SECTION("new_linux", "tracex4_kern.o", "kretprobe/kmem_cache_alloc_node")
TEST_SECTION("new_linux", "tracex6_kern.o", "kprobe/htab_map_get_next_key")
TEST_SECTION("new_linux", "tracex6_kern.o", "kprobe/htab_map_lookup_elem")
TEST_SECTION("new_linux", "tracex7_kern.o", "kprobe/open_ctree")
