// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'invalid'.
TEST_SECTION("invalid", "c049438cf649269921736e7306231385350dea58", ".text")
TEST_SECTION("invalid", "ef2e42c0bfcf4dab6b9c3926759365b6dfa73634", ".text")

// ===========================================================================
// Failure Cause Group: VerifierTypeTracking
// Group size: 38 tests (38 expected_failure, 0 skip).
// Root cause:
//   State refinement loses precise register type information across specific control-flow merges, so a pointer or
//   scalar register is later treated as an incompatible type.
// Representative example:
//   test: invalid/af99e766f6ba44fd7f2135c3e325c817224b99a3 xdp_prog
//   diagnostic: 13: Invalid type (r1.type == map_fd)
// Addressing direction:
//   Improve type-domain join or widen logic for pointer classes and preserve key path constraints through merges.
//   Start from the first failing instruction and inspect predecessor states.
// ===========================================================================
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 13: Invalid type (r1.type == map_fd)
TEST_SECTION_FAIL("invalid", "af99e766f6ba44fd7f2135c3e325c817224b99a3", "xdp_prog", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 13: Invalid type (r1.type == map_fd)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 60: Invalid type (r2.type in {ctx, stack, packet, shared})
TEST_SECTION_FAIL("invalid", "dac31099c3bb5b6395908c82cc8540e77a6a1849", "bind", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 60: Invalid type (r2.type in {ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 20: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 20: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/0", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/1", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/10", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/11", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/12", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/13", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/14", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/15", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/16", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/17", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/18", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/19", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/2", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/20", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/21", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/22", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/23", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/24", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/25", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/26", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/27", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/28", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/29", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/3", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/30", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/31", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/32", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/33", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 20: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/34", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 20: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/4", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/5", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/6", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/7", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/8", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")
// expected failure (VerifierTypeTracking):
//   reason: Known verifier limitation: register type refinement is too imprecise in this control-flow pattern.
//   diagnostic: 48: Invalid type (r1.type == ctx)
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/9", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 48: Invalid type (r1.type == ctx)")

// ===========================================================================
// Failure Cause Group: VerifierBoundsTracking
// Group size: 1 tests (1 expected_failure, 0 skip).
// Root cause:
//   Numeric range reasoning is too coarse for dependent bounds, so safe accesses fail range checks (packet size,
//   stack window, map value window).
// Representative example:
//   test: invalid/662b334a22904023c13f11008e072076a4f4d215 xdp
//   diagnostic: 12: Upper bound must be at most 20 (valid_access(r6.offset+24, width=4) for read)
// Addressing direction:
//   Strengthen interval propagation for correlated predicates and arithmetic-derived offsets, and keep relation
//   information across branches where possible.
// ===========================================================================
// expected failure (VerifierBoundsTracking):
//   reason: Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof.
//   diagnostic: 12: Upper bound must be at most 20 (valid_access(r6.offset+24, width=4) for read)
TEST_SECTION_FAIL("invalid", "662b334a22904023c13f11008e072076a4f4d215", "xdp", verify_test::VerifyIssueKind::VerifierBoundsTracking, "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. Diagnostic: 12: Upper bound must be at most 20 (valid_access(r6.offset+24, width=4) for read)")

// ===========================================================================
// Failure Cause Group: UnmarshalControlFlow
// Group size: 1 tests (1 expected_failure, 0 skip).
// Root cause:
//   Instruction unmarshaling cannot reconstruct a valid CFG for the extracted bytecode slice.
// Representative example:
//   test: invalid/invalid-lddw.o .text
//   diagnostic: unmarshaling error at 1: incomplete lddw
// Addressing direction:
//   Stabilize extraction and jump target mapping so every emitted instruction stream has valid in-range branch and
//   call targets.
// ===========================================================================
// expected failure (UnmarshalControlFlow):
//   reason: Known loader limitation: instruction unmarshaling cannot reconstruct this control-flow shape.
//   diagnostic: unmarshaling error at 1: incomplete lddw
TEST_SECTION_FAIL("invalid", "invalid-lddw.o", ".text", verify_test::VerifyIssueKind::UnmarshalControlFlow, "Known loader limitation: instruction unmarshaling cannot reconstruct this control-flow shape. Diagnostic: unmarshaling error at 1: incomplete lddw")

// ===========================================================================
// Failure Cause Group: ElfCoreRelocation
// Group size: 8 tests (0 expected_failure, 8 skip).
// Root cause:
//   CO-RE or BTF relocation payload is malformed or unsupported by current loader expectations.
// Representative example:
//   test: invalid/58087ea4ff41695f3186d628a3250b26dc8d237a cgroup/connect4
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
// Addressing direction:
//   Harden BTF or CO-RE parser compatibility and validation, or gate unsupported variants with explicit diagnostics.
// ===========================================================================
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "58087ea4ff41695f3186d628a3250b26dc8d237a", "cgroup/connect4", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "58087ea4ff41695f3186d628a3250b26dc8d237a", "cgroup/connect6", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "58087ea4ff41695f3186d628a3250b26dc8d237a", "cgroup/recv_accept4", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "58087ea4ff41695f3186d628a3250b26dc8d237a", "cgroup/recv_accept6", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "ab3408afd06d68dd7e73bf21bde38350d9751a78", "cgroup/connect4", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "ab3408afd06d68dd7e73bf21bde38350d9751a78", "cgroup/connect6", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "ab3408afd06d68dd7e73bf21bde38350d9751a78", "cgroup/recv_accept4", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
// skipped (ElfCoreRelocation):
//   reason: Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object.
//   diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0
TEST_SECTION_SKIP("invalid", "ab3408afd06d68dd7e73bf21bde38350d9751a78", "cgroup/recv_accept6", verify_test::VerifyIssueKind::ElfCoreRelocation, "Known loader limitation: CO-RE/BTF relocation payload is unsupported or malformed for this object. Diagnostic: Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0")
