// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'linux-selftests'.
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "add", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "and", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "cmpxchg", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "or", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "sub", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "xchg", 7)
TEST_PROGRAM("linux-selftests", "atomics.o", "raw_tp/sys_enter", "xor", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_acked", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_cong_avoid", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_cwnd_event", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_init", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_recalc_ssthresh", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_state", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_cubic.o", "struct_ops", "bpf_cubic_undo_cwnd", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_cong_avoid", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_cwnd_event", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_cwnd_undo", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_init", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_ssthresh", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_state", 7)
TEST_PROGRAM_REJECT("linux-selftests", "bpf_dctcp.o", "struct_ops", "bpf_dctcp_update_alpha", 7)
TEST_SECTION("linux-selftests", "fexit_sleep.o", "fentry/__x64_sys_nanosleep")
TEST_SECTION("linux-selftests", "fexit_sleep.o", "fexit/__x64_sys_nanosleep")
TEST_SECTION("linux-selftests", "get_cgroup_id_kern.o", "tracepoint/syscalls/sys_enter_nanosleep")
TEST_SECTION("linux-selftests", "loop1.o", "raw_tracepoint/kfree_skb")
TEST_SECTION("linux-selftests", "loop2.o", "raw_tracepoint/consume_skb")
TEST_SECTION("linux-selftests", "loop4.o", "socket")
TEST_SECTION("linux-selftests", "loop5.o", "socket")
TEST_SECTION_REJECT("linux-selftests", "map_ptr_kern.o", "cgroup_skb/egress")
TEST_SECTION("linux-selftests", "sockmap_parse_prog.o", "sk_skb1")
TEST_SECTION("linux-selftests", "sockmap_verdict_prog.o", "sk_skb2")
TEST_PROGRAM("linux-selftests", "tailcall1.o", "tc", "classifier_0", 4)
TEST_PROGRAM("linux-selftests", "tailcall1.o", "tc", "classifier_1", 4)
TEST_PROGRAM("linux-selftests", "tailcall1.o", "tc", "classifier_2", 4)
TEST_PROGRAM("linux-selftests", "tailcall1.o", "tc", "entry", 4)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "classifier_0", 6)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "classifier_1", 6)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "classifier_2", 6)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "classifier_3", 6)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "classifier_4", 6)
TEST_PROGRAM("linux-selftests", "tailcall2.o", "tc", "entry", 6)
TEST_PROGRAM("linux-selftests", "tailcall3.o", "tc", "classifier_0", 2)
TEST_PROGRAM("linux-selftests", "tailcall3.o", "tc", "entry", 2)
TEST_PROGRAM("linux-selftests", "test_global_func1.o", ".text", "f0", 4)
TEST_PROGRAM("linux-selftests", "test_global_func1.o", ".text", "f1", 4)
TEST_SECTION("linux-selftests", "test_global_func1.o", "tc")
TEST_PROGRAM("linux-selftests", "test_global_func_args.o", ".text", "baz", 3)
TEST_SECTION("linux-selftests", "test_global_func_args.o", "cgroup_skb/ingress")
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", ".text", "static_subprog", 3)
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", ".text", "static_subprog_lock", 3)
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", ".text", "static_subprog_unlock", 3)
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", "tc", "lock_static_subprog_call", 3)
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", "tc", "lock_static_subprog_lock", 3)
TEST_PROGRAM("linux-selftests", "test_spin_lock.o", "tc", "lock_static_subprog_unlock", 3)

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("linux-selftests", "bloom_filter_map.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "bloom_filter_map.o", "fentry/__x64_sys_getpgid", "check_bloom", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "bloom_filter_map.o", "fentry/__x64_sys_getpgid", "inner_map", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("linux-selftests", "freplace_get_constant.o", "freplace/get_constant",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_array_of_maps", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_cgroup_storage", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_cpumap", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_default_noinline", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_devmap", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_devmap_hash", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_hash_of_maps", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_lpm_trie", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_lru_percpu_hash", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_percpu_cgroup_storage", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_queue", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_reuseport_sockarray", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_ringbuf", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_sk_storage", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_sockhash", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_sockmap", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_stack", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "map_ptr_kern.o", ".text", "check_xskmap", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("linux-selftests", "socket_cookie_prog.o", "cgroup/connect6",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// Socket type not tracked through sockops context access
TEST_SECTION_FAIL("linux-selftests", "socket_cookie_prog.o", "sockops",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "test_global_func1.o", ".text", "f2", 4,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "test_global_func1.o", ".text", "f3", 4,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "test_global_func_args.o", ".text", "bar", 3,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("linux-selftests", "test_global_func_args.o", ".text", "foo", 3,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("linux-selftests", "kfree_skb.o", "fentry/eth_type_trans",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("linux-selftests", "kfree_skb.o", "fexit/eth_type_trans",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("linux-selftests", "kfree_skb.o", "tp_btf/kfree_skb",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("linux-selftests", "socket_cookie_prog.o", "fexit/inet_stream_connect",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)

// VerifierNullability:
// nullability tracking is too conservative on this path
TEST_SECTION_FAIL("linux-selftests", "test_spin_lock.o", "cgroup_skb/ingress",
                  verify_test::VerifyIssueKind::VerifierNullability)

// VerificationTimeout:
// Known algorithmic limitation: verification did not converge within the configured timeout
TEST_SECTION_SKIP("linux-selftests", "loop3.o", "raw_tracepoint/consume_skb",
                  verify_test::VerifyIssueKind::VerificationTimeout)
