// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'bcc'.
TEST_SECTION("bcc", "capable.bpf.o", "kprobe/cap_capable")
TEST_SECTION("bcc", "capable.bpf.o", "kretprobe/cap_capable")
TEST_SECTION("bcc", "exitsnoop.bpf.o", "tracepoint/sched/sched_process_exit")
TEST_SECTION("bcc", "filelife.bpf.o", "kprobe/vfs_unlink")
TEST_SECTION("bcc", "tcpconnect.bpf.o", "kprobe/tcp_v4_connect")
TEST_SECTION("bcc", "tcpconnect.bpf.o", "kprobe/tcp_v6_connect")

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "bashreadline.bpf.o", "uretprobe/readline", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/security_inode_create",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/vfs_create", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/vfs_open", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kretprobe/vfs_unlink", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("bcc", "oomkill.bpf.o", "kprobe/oom_kill_process", verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("bcc", "tcpconnect.bpf.o", "kretprobe/tcp_v4_connect",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("bcc", "tcpconnect.bpf.o", "kretprobe/tcp_v6_connect",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
