// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'cilium-core'.
TEST_PROGRAM("cilium-core", "bpf_alignchecker.o", "tc/tail", "tail_icmp6_handle_ns", 2)
TEST_PROGRAM("cilium-core", "bpf_alignchecker.o", "tc/tail", "tail_icmp6_send_time_exceeded", 2)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_drop_notify", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv4_from_host", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv4_from_netdev", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_nat_fwd_ipv4", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_nat_fwd_ipv6", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_icmp6_handle_ns", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_icmp6_send_time_exceeded", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_ipv4_dsr", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_ipv6_dsr", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_nat_egress_ipv6", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_rev_dnat_egress_ipv6", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_rev_dnat_ingress_ipv6", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_rev_dnat_ipv4", 28)
TEST_PROGRAM("cilium-core", "bpf_host.o", "tc/tail", "tail_srv6_decap", 28)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/entry", "cil_from_container", 4)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/entry", "cil_lxc_policy", 4)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/entry", "cil_lxc_policy_egress", 4)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/entry", "cil_to_container", 4)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_drop_notify", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_handle_arp", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_handle_ipv4", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_icmp6_handle_ns", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_icmp6_send_time_exceeded", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv4_ct_egress", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv4_ct_ingress", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv4_ct_ingress_policy_only", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv6_ct_egress", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv6_ct_ingress", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv6_ct_ingress_policy_only", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_ipv4_dsr", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_ipv6_dsr", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_nat_egress_ipv6", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_rev_dnat_egress_ipv6", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_rev_dnat_ingress_ipv6", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_rev_dnat_ipv4", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_policy_denied_ipv4", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_srv6_decap", 30)
TEST_PROGRAM("cilium-core", "bpf_lxc.o", "tc/tail", "tail_srv6_encap", 30)
TEST_SECTION("cilium-core", "bpf_network.o", "tc/entry")
TEST_SECTION("cilium-core", "bpf_network.o", "tc/tail")
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/entry", "cil_from_overlay", 2)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/entry", "cil_to_overlay", 2)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_drop_notify", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_arp", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_ipv4", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_nat_fwd_ipv4", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_nat_fwd_ipv6", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_icmp6_send_time_exceeded", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_ipv4_dsr", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_ipv6_dsr", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_nat_egress_ipv6", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_rev_dnat_egress_ipv6", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_rev_dnat_ingress_ipv6", 19)
TEST_PROGRAM("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_rev_dnat_ipv4", 19)
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/connect4")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/connect6")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/post_bind4")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/post_bind6")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/recvmsg4")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/sendmsg4")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/sendmsg6")
TEST_SECTION("cilium-core", "bpf_sock.o", "cgroup/sock_release")
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/entry", "cil_from_wireguard", 2)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/entry", "cil_to_wireguard", 2)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_drop_notify", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_ipv4", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_nat_fwd_ipv4", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_nat_fwd_ipv6", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_snat_fwd_ipv4", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_snat_fwd_ipv6", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_icmp6_send_time_exceeded", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_ipv4_dsr", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_ipv6_dsr", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_nat_egress_ipv6", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_rev_dnat_egress_ipv6", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_rev_dnat_ingress_ipv6", 17)
TEST_PROGRAM("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_rev_dnat_ipv4", 17)
TEST_PROGRAM("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_drop_notify", 12)

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", ".text", "__check_device_mtu", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", ".text", "__check_eth_header_length", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv4_cont_from_host", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv4_cont_from_netdev", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv6_cont_from_host", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv6_cont_from_netdev", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv6_from_host", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_ipv6_from_netdev", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_snat_fwd_ipv4", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_ipv4_host_policy_ingress", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_ipv6_host_policy_ingress", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_nat_ingress_ipv4", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_nat_ingress_ipv6", 28,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium-core", "bpf_lxc.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_handle_ipv4_cont", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_handle_ipv6", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_handle_ipv6_cont", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv4_policy", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv4_to_endpoint", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv6_policy", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_ipv6_to_endpoint", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_nat_ingress_ipv4", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_nat_ingress_ipv6", 30,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", ".text", "__check_device_mtu", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", ".text", "__mcast_ep_delivery", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_ipv6", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_snat_fwd_ipv4", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_handle_snat_fwd_ipv6", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_mcast_ep_delivery", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_nat_ingress_ipv4", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_nat_ingress_ipv6", 19,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium-core", "bpf_wireguard.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_handle_ipv6", 17,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_nat_ingress_ipv4", 17,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_nat_ingress_ipv6", 17,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium-core", "bpf_xdp.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/entry", "cil_from_host", 5,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/entry", "cil_from_netdev", 5,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/entry", "cil_host_policy", 5,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/entry", "cil_to_host", 5,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/entry", "cil_to_netdev", 5,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_srv6_encap", 28,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium-core", "bpf_xdp.o", "xdp/entry", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_lb_ipv4", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_lb_ipv6", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_ipv4_dsr", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_ipv6_dsr", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_nat_egress_ipv4", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_nat_egress_ipv6", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_nat_ingress_ipv4", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_nat_ingress_ipv6", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_rev_dnat_egress_ipv6", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_rev_dnat_ingress_ipv6", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_PROGRAM_FAIL("cilium-core", "bpf_xdp.o", "xdp/tail", "tail_nodeport_rev_dnat_ipv4", 12,
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)

// VerifierStackInitialization:
// stack initialization tracking is too coarse for this access path
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_nodeport_nat_egress_ipv4", 28,
                  verify_test::VerifyIssueKind::VerifierStackInitialization)
// stack initialization tracking is too coarse for this access path
TEST_PROGRAM_FAIL("cilium-core", "bpf_lxc.o", "tc/tail", "tail_nodeport_nat_egress_ipv4", 30,
                  verify_test::VerifyIssueKind::VerifierStackInitialization)
// stack initialization tracking is too coarse for this access path
TEST_PROGRAM_FAIL("cilium-core", "bpf_overlay.o", "tc/tail", "tail_nodeport_nat_egress_ipv4", 19,
                  verify_test::VerifyIssueKind::VerifierStackInitialization)
// stack initialization tracking is too coarse for this access path
TEST_PROGRAM_FAIL("cilium-core", "bpf_wireguard.o", "tc/tail", "tail_nodeport_nat_egress_ipv4", 17,
                  verify_test::VerifyIssueKind::VerifierStackInitialization)

// VerifierMapTyping:
// map value/key typing and scalarization are too conservative here
TEST_SECTION_FAIL("cilium-core", "bpf_sock.o", "cgroup/recvmsg6", verify_test::VerifyIssueKind::VerifierMapTyping)

// VerifierNullability:
// nullability tracking is too conservative on this path
TEST_PROGRAM_FAIL("cilium-core", "bpf_host.o", "tc/tail", "tail_handle_snat_fwd_ipv6", 28,
                  verify_test::VerifyIssueKind::VerifierNullability)
