// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_accept4_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_empty")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pread64_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_preadv64_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pwrite64_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_single_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sysdigevent_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/terminate_filler")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/page_fault_kernel")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/page_fault_user")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/sched_switch")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/signal_deliver")

TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_access_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_bpf_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_brk_munmap_mmap_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_eventfd_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_execve_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_generic")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getrlimit_setrlimit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getrlimit_setrlrimit_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_mount_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pagefault_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_procexit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_single")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_unshare_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/sched_process_exit")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_chmod_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_fchmod_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_fcntl_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_flock_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_prlimit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_prlimit_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_ptrace_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_quotactl_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_semop_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_send_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sendfile_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_setns_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_shutdown_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_fchmodat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_futex_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_lseek_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_mkdirat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_ptrace_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_quotactl_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_semget_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_signaldeliver_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_symlinkat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_unlinkat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_writev_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_llseek_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pwritev_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_renameat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_semctl_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sched_switch_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_linkat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_renameat2_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sendfile_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_setsockopt_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getresuid_and_gid_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_mmap_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_socket_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/sys_enter")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/sys_exit")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pipe_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_socketpair_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_creat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_open_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_openat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_autofill")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate_3")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate_2")

// Falco expected-fail group A (offset lower-bound loss):
// In these sections, a shared-pointer base is incremented by a scalar offset that
// is only upper-bounded by control-flow assumptions. At merge points, the scalar's
// lower bound is lost, so valid_access(..., write) cannot prove offset >= 0.
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_nanosleep_e")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_poll_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_poll_e")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_ppoll_e")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_getsockopt_x")

// Falco expected-fail group B (size lower-bound loss at correlated joins):
// Common pattern:
// 1) branch constrains size_candidate (e.g., assume const > r2)
// 2) alternate branch writes a concrete fallback size
// 3) join loses the branch/value correlation and retains only size <= const
// Then ValidSize for probe_read* cannot prove r2 >= 0.
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_socket_bind_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvmsg_x_2")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendmsg_e")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_connect_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendto_e")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_accept_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_read_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recv_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvmsg_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_send_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_readv_preadv_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_write_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_writev_pwritev_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendmsg_x")
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvfrom_x")
