// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'cilium-examples'.
TEST_SECTION("cilium-examples", "cgroup_skb_bpf_bpfel.o", "cgroup_skb/egress")
TEST_SECTION("cilium-examples", "kprobe_bpf_bpfel.o", "kprobe/sys_execve")
TEST_SECTION("cilium-examples", "kprobe_percpu_bpf_bpfel.o", "kprobe/sys_execve")
TEST_SECTION("cilium-examples", "kprobepin_bpf_bpfel.o", "kprobe/sys_execve")
TEST_PROGRAM("cilium-examples", "tcx_bpf_bpfel.o", "tc", "egress_prog_func", 2)
TEST_PROGRAM("cilium-examples", "tcx_bpf_bpfel.o", "tc", "ingress_prog_func", 2)
TEST_SECTION("cilium-examples", "tracepoint_in_c_bpf_bpfel.o", "tracepoint/kmem/mm_page_alloc")
TEST_SECTION("cilium-examples", "xdp_bpf_bpfel.o", "xdp")

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium-examples", "ringbuffer_bpf_bpfel.o", "kprobe/sys_execve",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium-examples", "uretprobe_bpf_x86_bpfel.o", "uretprobe/bash_readline",
                  verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium-examples", "fentry_bpf_bpfel.o", "fentry/tcp_connect",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium-examples", "tcprtt_bpf_bpfel.o", "fentry/tcp_close",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium-examples", "tcprtt_sockops_bpf_bpfel.o", "sockops",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
