// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'bcc'.
TEST_SECTION("bcc", "capable.bpf.o", "kprobe/cap_capable")
TEST_SECTION("bcc", "capable.bpf.o", "kretprobe/cap_capable")
TEST_SECTION("bcc", "exitsnoop.bpf.o", "tracepoint/sched/sched_process_exit")
TEST_SECTION("bcc", "filelife.bpf.o", "kprobe/vfs_unlink")
TEST_SECTION("bcc", "tcpconnect.bpf.o", "kprobe/tcp_v4_connect")
TEST_SECTION("bcc", "tcpconnect.bpf.o", "kprobe/tcp_v6_connect")

// ===========================================================================
// Failure Cause Group: VerifierTypeTracking
// Group size: 6 tests (6 expected_failure, 0 skip).
// Root cause:
//   State refinement loses precise register type information across specific control-flow merges, so a pointer or
//   scalar register is later treated as an incompatible type.
// Representative example:
//   test: bcc/bashreadline.bpf.o uretprobe/readline
//   diagnostic: 2: Invalid type (valid_access(r7.offset) for comparison/subtraction)
// Addressing direction:
//   Improve type-domain join or widen logic for pointer classes and preserve key path constraints through merges.
//   Start from the first failing instruction and inspect predecessor states.
// ===========================================================================
// expected failure (VerifierTypeTracking):
//   diagnostic: 2: Invalid type (valid_access(r7.offset) for comparison/subtraction)
TEST_SECTION_FAIL("bcc", "bashreadline.bpf.o", "uretprobe/readline", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 2: Invalid type (valid_access(r7.offset) for comparison/subtraction)")
// expected failure (VerifierTypeTracking):
//   diagnostic: 17: Invalid type (r6.type in {number, ctx, stack, packet, shared})
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/security_inode_create",
                  verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 17: Invalid type (r6.type in {number, ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   diagnostic: 34: Invalid type (r6.type in {number, ctx, stack, packet, shared})
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/vfs_create", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 34: Invalid type (r6.type in {number, ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   diagnostic: 35: Invalid type (r6.type in {number, ctx, stack, packet, shared})
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kprobe/vfs_open", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 35: Invalid type (r6.type in {number, ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   diagnostic: 38: Invalid type (r7.type in {ctx, stack, packet, shared})
TEST_SECTION_FAIL("bcc", "filelife.bpf.o", "kretprobe/vfs_unlink", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 38: Invalid type (r7.type in {ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   diagnostic: 21: Invalid type (r7.type in {ctx, stack, packet, shared})
TEST_SECTION_FAIL("bcc", "oomkill.bpf.o", "kprobe/oom_kill_process", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 21: Invalid type (r7.type in {ctx, stack, packet, shared})")

// ===========================================================================
// Failure Cause Group: VerifierBoundsTracking
// Group size: 2 tests (2 expected_failure, 0 skip).
// Root cause:
//   Numeric range reasoning is too coarse for dependent bounds, so safe accesses fail range checks (packet size,
//   stack window, map value window).
// Representative example:
//   test: bcc/tcpconnect.bpf.o kretprobe/tcp_v4_connect
//   diagnostic: 57: Upper bound must be at most r1.shared_region_size (valid_access(r1.offset, width=4) for read)
// Addressing direction:
//   Strengthen interval propagation for correlated predicates and arithmetic-derived offsets, and keep relation
//   information across branches where possible.
// ===========================================================================
// expected failure (VerifierBoundsTracking):
//   diagnostic: 57: Upper bound must be at most r1.shared_region_size (valid_access(r1.offset, width=4) for read)
TEST_SECTION_FAIL(
    "bcc", "tcpconnect.bpf.o", "kretprobe/tcp_v4_connect", verify_test::VerifyIssueKind::VerifierBoundsTracking,
    "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. Diagnostic: "
    "57: Upper bound must be at most r1.shared_region_size (valid_access(r1.offset, width=4) for read)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 57: Upper bound must be at most r1.shared_region_size (valid_access(r1.offset, width=4) for read)
TEST_SECTION_FAIL(
    "bcc", "tcpconnect.bpf.o", "kretprobe/tcp_v6_connect", verify_test::VerifyIssueKind::VerifierBoundsTracking,
    "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. Diagnostic: "
    "57: Upper bound must be at most r1.shared_region_size (valid_access(r1.offset, width=4) for read)")
