// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT
// Auto-generated test file for project: falco
#include "test_verify.hpp"

TEST_CASE("falco/probe.o", "[verify][samples][falco]") {
    static const FileEntry file = {
        "probe.o",
        {
            {.section = "raw_tracepoint/filler/terminate_filler"},
            {.section = "raw_tracepoint/filler/sys_empty"},
            {.section = "raw_tracepoint/filler/sys_single"},
            {.section = "raw_tracepoint/filler/sys_single_x"},
            {.section = "raw_tracepoint/filler/sys_open_x"},
            {.section = "raw_tracepoint/filler/sys_read_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_write_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_poll_e", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_poll_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_readv_preadv_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_writev_e"},
            {.section = "raw_tracepoint/filler/sys_writev_pwritev_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_nanosleep_e", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_futex_e"},
            {.section = "raw_tracepoint/filler/sys_brk_munmap_mmap_x"},
            {.section = "raw_tracepoint/filler/sys_mmap_e"},
            {.section = "raw_tracepoint/filler/sys_fcntl_e"},
            {.section = "raw_tracepoint/filler/sys_access_e"},
            {.section = "raw_tracepoint/filler/sys_getrlimit_setrlimit_e"},
            {.section = "raw_tracepoint/filler/sys_getrlimit_setrlrimit_x"},
            {.section = "raw_tracepoint/filler/sys_connect_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_socketpair_x"},
            {.section = "raw_tracepoint/filler/sys_setsockopt_x"},
            {.section = "raw_tracepoint/filler/sys_getsockopt_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_send_e"},
            {.section = "raw_tracepoint/filler/sys_sendto_e", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_send_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_execve_e"},
            {.section = "raw_tracepoint/filler/proc_startupdate"},
            {.section = "raw_tracepoint/filler/proc_startupdate_2"},
            {.section = "raw_tracepoint/filler/proc_startupdate_3"},
            {.section = "raw_tracepoint/filler/sys_accept4_e"},
            {.section = "raw_tracepoint/filler/sys_accept_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_setns_e"},
            {.section = "raw_tracepoint/filler/sys_unshare_e"},
            {.section = "raw_tracepoint/filler/sys_generic"},
            {.section = "raw_tracepoint/filler/sys_openat_x"},
            {.section = "raw_tracepoint/filler/sys_sendfile_e"},
            {.section = "raw_tracepoint/filler/sys_sendfile_x"},
            {.section = "raw_tracepoint/filler/sys_prlimit_e"},
            {.section = "raw_tracepoint/filler/sys_prlimit_x"},
            {.section = "raw_tracepoint/filler/sys_pwritev_e"},
            {.section = "raw_tracepoint/filler/sys_getresuid_and_gid_x"},
            {.section = "raw_tracepoint/filler/sys_socket_bind_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_recv_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_recvfrom_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_shutdown_e"},
            {.section = "raw_tracepoint/filler/sys_recvmsg_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_recvmsg_x_2", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_sendmsg_e", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_sendmsg_x", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_creat_x"},
            {.section = "raw_tracepoint/filler/sys_pipe_x"},
            {.section = "raw_tracepoint/filler/sys_lseek_e"},
            {.section = "raw_tracepoint/filler/sys_llseek_e"},
            {.section = "raw_tracepoint/filler/sys_eventfd_e"},
            {.section = "raw_tracepoint/filler/sys_mount_e"},
            {.section = "raw_tracepoint/filler/sys_ppoll_e", .expect = Expect::Xfail},
            {.section = "raw_tracepoint/filler/sys_semop_x"},
            {.section = "raw_tracepoint/filler/sys_socket_x"},
            {.section = "raw_tracepoint/filler/sys_flock_e"},
            {.section = "raw_tracepoint/filler/sys_pread64_e"},
            {.section = "raw_tracepoint/filler/sys_preadv64_e"},
            {.section = "raw_tracepoint/filler/sys_pwrite64_e"},
            {.section = "raw_tracepoint/filler/sys_renameat_x"},
            {.section = "raw_tracepoint/filler/sys_renameat2_x"},
            {.section = "raw_tracepoint/filler/sys_symlinkat_x"},
            {.section = "raw_tracepoint/filler/sys_sysdigevent_e"},
            {.section = "raw_tracepoint/filler/cpu_hotplug_e"},
            {.section = "raw_tracepoint/filler/sched_drop"},
            {.section = "raw_tracepoint/filler/sys_procexit_e"},
            {.section = "raw_tracepoint/filler/sched_switch_e"},
            {.section = "raw_tracepoint/filler/sys_pagefault_e"},
            {.section = "raw_tracepoint/filler/sys_signaldeliver_e"},
            {.section = "raw_tracepoint/filler/sys_quotactl_e"},
            {.section = "raw_tracepoint/filler/sys_quotactl_x"},
            {.section = "raw_tracepoint/filler/sys_semget_e"},
            {.section = "raw_tracepoint/filler/sys_semctl_e"},
            {.section = "raw_tracepoint/filler/sys_ptrace_e"},
            {.section = "raw_tracepoint/filler/sys_ptrace_x"},
            {.section = "raw_tracepoint/filler/sys_bpf_x"},
            {.section = "raw_tracepoint/filler/sys_unlinkat_x"},
            {.section = "raw_tracepoint/filler/sys_mkdirat_x"},
            {.section = "raw_tracepoint/filler/sys_linkat_x"},
            {.section = "raw_tracepoint/filler/sys_autofill"},
            {.section = "raw_tracepoint/filler/sys_fchmodat_x"},
            {.section = "raw_tracepoint/filler/sys_chmod_x"},
            {.section = "raw_tracepoint/filler/sys_fchmod_x"},
            {.section = "raw_tracepoint/sys_enter"},
            {.section = "raw_tracepoint/sys_exit"},
            {.section = "raw_tracepoint/sched_process_exit"},
            {.section = "raw_tracepoint/sched_switch"},
            {.section = "raw_tracepoint/page_fault_user"},
            {.section = "raw_tracepoint/page_fault_kernel"},
            {.section = "raw_tracepoint/signal_deliver"},
        }};
    verify_file("falco", file);
}
