// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'invalid'.
TEST_CASE("invalid/58087ea4ff41695f3186d628a3250b26dc8d237a cgroup/connect4", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/58087ea4ff41695f3186d628a3250b26dc8d237a cgroup/connect6", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/58087ea4ff41695f3186d628a3250b26dc8d237a cgroup/recv_accept4", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/58087ea4ff41695f3186d628a3250b26dc8d237a cgroup/recv_accept6", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
// expected failure: check exit 1: 0,0.000857302,5920
TEST_SECTION_FAIL("invalid", "662b334a22904023c13f11008e072076a4f4d215", "xdp")
TEST_CASE("invalid/ab3408afd06d68dd7e73bf21bde38350d9751a78 cgroup/connect4", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/ab3408afd06d68dd7e73bf21bde38350d9751a78 cgroup/connect6", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/ab3408afd06d68dd7e73bf21bde38350d9751a78 cgroup/recv_accept4", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
TEST_CASE("invalid/ab3408afd06d68dd7e73bf21bde38350d9751a78 cgroup/recv_accept6", "[verify][samples][invalid]") {
    SKIP("Unsupported or invalid CO-RE/BTF relocation data: Invalid .BTF section - invalid BTF_KIND - 0");
}
// expected failure: check exit 1: 0,0.000625535,6080
TEST_SECTION_FAIL("invalid", "af99e766f6ba44fd7f2135c3e325c817224b99a3", "xdp_prog")
TEST_SECTION("invalid", "c049438cf649269921736e7306231385350dea58", ".text")
// expected failure: check exit 1: 0,0.0078959,8640
TEST_SECTION_FAIL("invalid", "dac31099c3bb5b6395908c82cc8540e77a6a1849", "bind")
TEST_SECTION("invalid", "ef2e42c0bfcf4dab6b9c3926759365b6dfa73634", ".text")
// expected failure: check exit 1: unmarshaling error at 1: incomplete lddw
TEST_SECTION_FAIL("invalid", "invalid-lddw.o", ".text")
// expected failure: check exit 1: 0,0.000613432,5920
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind")
// expected failure: check exit 1: 0,0.00148721,6880
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/0")
// expected failure: check exit 1: 0,0.00147774,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/1")
// expected failure: check exit 1: 0,0.00135264,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/10")
// expected failure: check exit 1: 0,0.00150479,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/11")
// expected failure: check exit 1: 0,0.00148999,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/12")
// expected failure: check exit 1: 0,0.00146089,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/13")
// expected failure: check exit 1: 0,0.00148259,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/14")
// expected failure: check exit 1: 0,0.00149265,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/15")
// expected failure: check exit 1: 0,0.00144562,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/16")
// expected failure: check exit 1: 0,0.00141163,6240
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/17")
// expected failure: check exit 1: 0,0.00137354,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/18")
// expected failure: check exit 1: 0,0.00146723,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/19")
// expected failure: check exit 1: 0,0.00146562,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/2")
// expected failure: check exit 1: 0,0.00143148,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/20")
// expected failure: check exit 1: 0,0.00151853,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/21")
// expected failure: check exit 1: 0,0.00165074,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/22")
// expected failure: check exit 1: 0,0.001439,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/23")
// expected failure: check exit 1: 0,0.00142574,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/24")
// expected failure: check exit 1: 0,0.00143288,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/25")
// expected failure: check exit 1: 0,0.00146502,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/26")
// expected failure: check exit 1: 0,0.00151092,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/27")
// expected failure: check exit 1: 0,0.00138598,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/28")
// expected failure: check exit 1: 0,0.00138095,6400
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/29")
// expected failure: check exit 1: 0,0.00155026,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/3")
// expected failure: check exit 1: 0,0.00145247,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/30")
// expected failure: check exit 1: 0,0.0017359,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/31")
// expected failure: check exit 1: 0,0.00162887,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/32")
// expected failure: check exit 1: 0,0.00145282,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/33")
// expected failure: check exit 1: 0,0.000489861,5760
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/34")
// expected failure: check exit 1: 0,0.00143513,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/4")
// expected failure: check exit 1: 0,0.00140039,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/5")
// expected failure: check exit 1: 0,0.00142489,6560
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/6")
// expected failure: check exit 1: 0,0.00148781,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/7")
// expected failure: check exit 1: 0,0.0013985,6240
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/8")
// expected failure: check exit 1: 0,0.00140423,6720
TEST_SECTION_FAIL("invalid", "timeout-29db93548c671165313b314d4f83a3eefa24df37", "bind/9")
