// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'libbpf-bootstrap'.
TEST_SECTION("libbpf-bootstrap", "bootstrap_legacy.bpf.o", "tp/sched/sched_process_exit")
TEST_SECTION("libbpf-bootstrap", "kprobe.bpf.o", "kprobe/do_unlinkat")
TEST_SECTION("libbpf-bootstrap", "kprobe.bpf.o", "kretprobe/do_unlinkat")
TEST_SECTION("libbpf-bootstrap", "minimal.bpf.o", "tp/syscalls/sys_enter_write")
TEST_SECTION("libbpf-bootstrap", "minimal_legacy.bpf.o", "tp/syscalls/sys_enter_write")
TEST_SECTION("libbpf-bootstrap", "minimal_ns.bpf.o", "tp/syscalls/sys_enter_write")
TEST_SECTION("libbpf-bootstrap", "tc.bpf.o", "tc")
TEST_SECTION("libbpf-bootstrap", "uprobe.bpf.o", "uprobe")
TEST_SECTION("libbpf-bootstrap", "uprobe.bpf.o", "uprobe//proc/self/exe:uprobed_sub")
TEST_SECTION("libbpf-bootstrap", "uprobe.bpf.o", "uretprobe")
TEST_SECTION("libbpf-bootstrap", "uprobe.bpf.o", "uretprobe//proc/self/exe:uprobed_sub")
TEST_PROGRAM("libbpf-bootstrap", "usdt.bpf.o", ".text", "bpf_usdt_arg_cnt", 3)
TEST_PROGRAM("libbpf-bootstrap", "usdt.bpf.o", ".text", "bpf_usdt_cookie", 3)

// ===========================================================================
// Failure Cause Group: VerifierTypeTracking
// Group size: 4 tests (4 expected_failure, 0 skip).
// Root cause:
//   State refinement loses precise register type information across specific control-flow merges, so a pointer or
//   scalar register is later treated as an incompatible type.
// Representative example:
//   test: libbpf-bootstrap/bootstrap_legacy.bpf.o tp/sched/sched_process_exec
//   diagnostic: 70: Invalid type (r3.type == number)
// Addressing direction:
//   Improve type-domain join or widen logic for pointer classes and preserve key path constraints through merges.
//   Start from the first failing instruction and inspect predecessor states.
// ===========================================================================
// expected failure (VerifierTypeTracking):
//   diagnostic: 70: Invalid type (r3.type == number)
TEST_SECTION_FAIL("libbpf-bootstrap", "bootstrap_legacy.bpf.o", "tp/sched/sched_process_exec",
                  verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 70: Invalid type (r3.type == number)")
// expected failure (VerifierTypeTracking):
//   diagnostic: 4: Invalid type (r6.type in {ctx, stack, packet, shared})
TEST_PROGRAM_FAIL("libbpf-bootstrap", "usdt.bpf.o", ".text", "bpf_usdt_arg", 3,
                  verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 4: Invalid type (r6.type in {ctx, stack, packet, shared})")
// expected failure (VerifierTypeTracking):
//   diagnostic: 10/83: Invalid type (r3.type == number)
TEST_SECTION_FAIL("libbpf-bootstrap", "usdt.bpf.o", "usdt", verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 10/83: Invalid type (r3.type == number)")
// expected failure (VerifierTypeTracking):
//   diagnostic: 10/90: Invalid type (r3.type == number)
TEST_SECTION_FAIL("libbpf-bootstrap", "usdt.bpf.o", "usdt/libc.so.6:libc:setjmp",
                  verify_test::VerifyIssueKind::VerifierTypeTracking,
                  "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. "
                  "Diagnostic: 10/90: Invalid type (r3.type == number)")

// ===========================================================================
// Failure Cause Group: VerifierBoundsTracking
// Group size: 8 tests (8 expected_failure, 0 skip).
// Root cause:
//   Numeric range reasoning is too coarse for dependent bounds, so safe accesses fail range checks (packet size,
//   stack window, map value window).
// Representative example:
//   test: libbpf-bootstrap/bootstrap.bpf.o tp/sched/sched_process_exec
//   diagnostic: 24: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)
// Addressing direction:
//   Strengthen interval propagation for correlated predicates and arithmetic-derived offsets, and keep relation
//   information across branches where possible.
// ===========================================================================
// expected failure (VerifierBoundsTracking):
//   diagnostic: 24: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)
TEST_SECTION_FAIL("libbpf-bootstrap", "bootstrap.bpf.o", "tp/sched/sched_process_exec",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 24: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 39: Lower bound must be at least 0 (valid_access(r6.offset) for comparison/subtraction)
TEST_SECTION_FAIL("libbpf-bootstrap", "bootstrap.bpf.o", "tp/sched/sched_process_exit",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 39: Lower bound must be at least 0 (valid_access(r6.offset) for comparison/subtraction)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset+8, width=8) for read)
TEST_SECTION_FAIL("libbpf-bootstrap", "fentry.bpf.o", "fentry/do_unlinkat",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset+8, width=8) for read)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset+16, width=8) for read)
TEST_SECTION_FAIL("libbpf-bootstrap", "fentry.bpf.o", "fexit/do_unlinkat",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset+16, width=8) for read)")
// Previously failed because LSM used g_unspec_descr (size=0), rejecting all context accesses.
// Now passes with g_tracing_descr (size=96).
TEST_SECTION("libbpf-bootstrap", "lsm.bpf.o", "lsm/bpf")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 12: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)
TEST_SECTION_FAIL("libbpf-bootstrap", "profile.bpf.o", "perf_event",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 12: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 27: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)
TEST_SECTION_FAIL("libbpf-bootstrap", "sockfilter.bpf.o", "socket",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 27: Lower bound must be at least 0 (valid_access(r7.offset) for comparison/subtraction)")
// expected failure (VerifierBoundsTracking):
//   diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset, width=8) for read)
TEST_SECTION_FAIL("libbpf-bootstrap", "task_iter.bpf.o", "iter/task",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking,
                  "Known verifier limitation: interval/bounds refinement loses precision for this memory-access proof. "
                  "Diagnostic: 0: Upper bound must be at most 0 (valid_access(r1.offset, width=8) for read)")

// ===========================================================================
// Failure Cause Group: VerifierStackInitialization
// Group size: 2 tests (2 expected_failure, 0 skip).
// Root cause:
//   Stack byte initialization tracking misses writes or invalidates facts too aggressively, so reads are reported as
//   non-numeric or uninitialized.
// Representative example:
//   test: libbpf-bootstrap/ksyscall.bpf.o ksyscall/kill
//   diagnostic: 54: Stack content is not numeric ((r3.type == number and r3.value == 0) or valid_access(r3.offset,
//               width=r4) for read)
// Addressing direction:
//   Tighten per-byte initialization transfer functions and join behavior for stack slots touched through aliases and
//   conditional writes.
// ===========================================================================
// expected failure (VerifierStackInitialization):
//   diagnostic: 54: Stack content is not numeric ((r3.type == number and r3.value == 0) or valid_access(r3.offset,
//               width=r4) for read)
TEST_SECTION_FAIL("libbpf-bootstrap", "ksyscall.bpf.o", "ksyscall/kill",
                  verify_test::VerifyIssueKind::VerifierStackInitialization,
                  "Known verifier limitation: stack initialization tracking is too coarse for this access path. "
                  "Diagnostic: 54: Stack content is not numeric ((r3.type == number and r3.value == 0) or "
                  "valid_access(r3.offset, width=r4) for read)")
// expected failure (VerifierStackInitialization):
//   diagnostic: 81: Stack content is not numeric ((r3.type == number and r3.value == 0) or valid_access(r3.offset,
//               width=r4) for read)
TEST_SECTION_FAIL("libbpf-bootstrap", "ksyscall.bpf.o", "ksyscall/tgkill",
                  verify_test::VerifyIssueKind::VerifierStackInitialization,
                  "Known verifier limitation: stack initialization tracking is too coarse for this access path. "
                  "Diagnostic: 81: Stack content is not numeric ((r3.type == number and r3.value == 0) or "
                  "valid_access(r3.offset, width=r4) for read)")
