// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'falco'.
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/cpu_hotplug_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate_2")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/proc_startupdate_3")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sched_drop")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sched_switch_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_accept4_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_access_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_autofill")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_bpf_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_brk_munmap_mmap_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_chmod_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_creat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_empty")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_eventfd_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_execve_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_fchmod_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_fchmodat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_fcntl_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_flock_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_futex_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_generic")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getresuid_and_gid_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getrlimit_setrlimit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_getrlimit_setrlrimit_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_linkat_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_llseek_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_lseek_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_mkdirat_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_mmap_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_mount_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_open_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_openat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pagefault_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_pipe_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pread64_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_preadv64_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_prlimit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_prlimit_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_procexit_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_ptrace_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_ptrace_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_pwrite64_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_pwritev_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_quotactl_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_quotactl_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_renameat2_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_renameat_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_semctl_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_semget_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_semop_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_send_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sendfile_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sendfile_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_setns_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_setsockopt_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_shutdown_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_signaldeliver_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_single")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_single_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_socket_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_socketpair_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_symlinkat_x")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/sys_sysdigevent_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_unlinkat_x")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_unshare_e")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/filler/sys_writev_e")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/filler/terminate_filler")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/page_fault_kernel")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/page_fault_user")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/sched_process_exit")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/sched_switch")
TEST_SECTION("falco", "probe.o", "raw_tracepoint/signal_deliver")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/sys_enter")
// Intentional stricter memory-initialization policy: this sample reads or passes stack bytes that are not proven
// initialized; helper output success or stack padding is not treated as initialized by default.
TEST_SECTION_REJECT("falco", "probe.o", "raw_tracepoint/sys_exit")

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_accept_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_connect_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_getsockopt_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_nanosleep_e",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_poll_e",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_poll_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_ppoll_e",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_read_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_readv_preadv_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recv_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvfrom_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvmsg_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_recvmsg_x_2",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_send_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendmsg_e",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendmsg_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_sendto_e",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_socket_bind_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_write_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("falco", "probe.o", "raw_tracepoint/filler/sys_writev_pwritev_x",
                  verify_test::VerifyIssueKind::VerifierBoundsTracking)
