// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'cilium'.
TEST_SECTION("cilium", "bpf_lb.o", "2/1")
TEST_SECTION("cilium", "bpf_lb.o", "from-netdev")
TEST_SECTION("cilium", "bpf_lxc.o", "1/0x1010")
TEST_SECTION("cilium", "bpf_lxc.o", "2/1")
TEST_SECTION("cilium", "bpf_lxc.o", "2/10")
TEST_SECTION("cilium", "bpf_lxc.o", "2/11")
TEST_SECTION("cilium", "bpf_lxc.o", "2/12")
TEST_SECTION("cilium", "bpf_lxc.o", "2/3")
TEST_SECTION("cilium", "bpf_lxc.o", "2/4")
TEST_SECTION("cilium", "bpf_lxc.o", "2/5")
TEST_SECTION("cilium", "bpf_lxc.o", "2/6")
TEST_SECTION("cilium", "bpf_lxc.o", "2/7")
TEST_SECTION("cilium", "bpf_lxc.o", "2/8")
TEST_SECTION("cilium", "bpf_lxc.o", "2/9")
TEST_SECTION("cilium", "bpf_lxc.o", "from-container")
TEST_SECTION("cilium", "bpf_netdev.o", "2/1")
TEST_SECTION("cilium", "bpf_netdev.o", "2/3")
TEST_SECTION("cilium", "bpf_netdev.o", "2/4")
TEST_SECTION("cilium", "bpf_netdev.o", "2/5")
TEST_SECTION("cilium", "bpf_netdev.o", "2/7")
TEST_SECTION("cilium", "bpf_netdev.o", "from-netdev")
TEST_SECTION("cilium", "bpf_overlay.o", "2/1")
TEST_SECTION("cilium", "bpf_overlay.o", "2/3")
TEST_SECTION("cilium", "bpf_overlay.o", "2/4")
TEST_SECTION("cilium", "bpf_overlay.o", "2/5")
TEST_SECTION("cilium", "bpf_overlay.o", "2/7")
TEST_SECTION("cilium", "bpf_overlay.o", "from-overlay")
TEST_SECTION("cilium", "bpf_xdp.o", "from-netdev")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux.o", "2/1")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux.o", "from-netdev")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux_v1.o", "2/1")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux_v1.o", "from-netdev")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/1")
TEST_SECTION("cilium", "bpf_xdp_dsr_linux_v1_1.o", "from-netdev")
TEST_SECTION("cilium", "bpf_xdp_snat_linux.o", "2/1")
TEST_SECTION("cilium", "bpf_xdp_snat_linux.o", "from-netdev")
TEST_SECTION("cilium", "bpf_xdp_snat_linux_v1.o", "2/1")
TEST_SECTION("cilium", "bpf_xdp_snat_linux_v1.o", "from-netdev")

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/16", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/24", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/16", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/24", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/16", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/24", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/16", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/24", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/16", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/24", verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/10", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/15", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/17", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/18", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/19", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/20", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/21", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux.o", "2/7", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/10", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/15", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/17", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/18", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/19", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/20", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/21", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1.o", "2/7", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/10", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/15", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/17", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/18", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/19", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/20", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/21", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_dsr_linux_v1_1.o", "2/7", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/10", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/15", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/17", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/18", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/19", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux.o", "2/7", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/10", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/15", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/17", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/18", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/19", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("cilium", "bpf_xdp_snat_linux_v1.o", "2/7", verify_test::VerifyIssueKind::VerifierBoundsTracking)
