// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'build'.
// expected failure: check exit 1: 0,0.000452691,5600
TEST_SECTION_FAIL("build", "badhelpercall.o", ".text")
// expected failure: check exit 1: 0,0.000270188,5440
TEST_SECTION_FAIL("build", "badmapptr.o", "test")
TEST_CASE("build/badrelo.o .text", "[verify][samples][build]") { SKIP("Subprogram not found: ebpf_map_update_elem"); }
TEST_SECTION("build", "bounded_loop.o", "test")
TEST_CASE("build/bpf2bpf.o .text", "[verify][samples][build]") { SKIP("multi-program section (2 programs)"); }
TEST_SECTION("build", "bpf2bpf.o", "test")
// expected failure: check exit 1: 0,0.000551208,5600
TEST_SECTION_FAIL("build", "bpf_loop_helper.o", ".text")
// expected failure: check exit 1: 0,0.000356817,5600
TEST_SECTION_FAIL("build", "bpf_loop_helper.o", "xdp")
TEST_SECTION("build", "byteswap.o", ".text")
// expected failure: check exit 1: 0,0.00119015,6080
TEST_SECTION_FAIL("build", "correlated_branch.o", "xdp")
// expected failure: check exit 1: 0,0.00219839,6720
TEST_SECTION_FAIL("build", "correlated_branch2.o", "socket_filter")
TEST_SECTION("build", "cpumap.o", "xdp")
// expected failure: check exit 1: 0,0.000384967,5760
TEST_SECTION_FAIL("build", "ctxoffset.o", "sockops")
// expected failure: check exit 1: 0,0.000690502,5600
TEST_SECTION_FAIL("build", "dependent_read.o", "xdp")
TEST_SECTION("build", "devmap.o", "xdp")
TEST_SECTION("build", "divzero.o", "test")
// expected failure: check exit 1: 0,0.000394879,5760
TEST_SECTION_FAIL("build", "exposeptr.o", ".text")
// expected failure: check exit 1: 0,0.000375482,5920
TEST_SECTION_FAIL("build", "exposeptr2.o", ".text")
TEST_CASE("build/externalfunction.o .text", "[verify][samples][build]") {
    SKIP("Subprogram not found: bpf_map_lookup_elem");
}
TEST_CASE("build/global_func.o .text", "[verify][samples][build]") { SKIP("multi-program section (2 programs)"); }
TEST_SECTION("build", "global_func.o", "xdp")
TEST_SECTION("build", "global_variable.o", ".text")
TEST_SECTION("build", "global_variable_2.o", ".text")
TEST_SECTION("build", "hash_of_maps.o", ".text")
TEST_SECTION("build", "infinite_loop.o", "test")
// expected failure: check exit 1: 0,0.000852341,5760
TEST_SECTION_FAIL("build", "invalid_map_access.o", ".text")
// expected failure: check exit 1: 0,0.00426658,6560
TEST_SECTION_FAIL("build", "loop.o", "test_md")
TEST_SECTION("build", "lpm_trie.o", "xdp")
TEST_SECTION("build", "map_in_map.o", ".text")
TEST_SECTION("build", "map_in_map_anonymous.o", ".text")
TEST_SECTION("build", "map_in_map_legacy.o", ".text")
TEST_SECTION("build", "map_in_map_typedef.o", ".text")
TEST_SECTION("build", "mapoverflow.o", ".text")
TEST_SECTION("build", "mapunderflow.o", ".text")
// expected failure: check exit 1: 0,0.000477452,5920
TEST_SECTION_FAIL("build", "mapvalue-overrun.o", ".text")
// expected failure: check exit 1: 0,0.000356177,5600
TEST_SECTION_FAIL("build", "nullmapref.o", "test")
TEST_SECTION("build", "packet_access.o", "xdp")
// expected failure: check exit 1: 0,0.000342057,5760
TEST_SECTION_FAIL("build", "packet_overflow.o", "xdp")
// expected failure: check exit 1: 0,0.000699083,5920
TEST_SECTION_FAIL("build", "packet_reallocate.o", "socket_filter")
TEST_SECTION("build", "packet_start_ok.o", "xdp")
TEST_SECTION("build", "percpu_array.o", "xdp")
TEST_SECTION("build", "percpu_hash.o", "xdp")
// expected failure: check exit 1: 0,0.000546048,5920
TEST_SECTION_FAIL("build", "perf_event_array.o", "xdp")
TEST_CASE("build/prog_array.o .text", "[verify][samples][build]") { SKIP("multi-program section (5 programs)"); }
// expected failure: check exit 1: 0,0.000269968,5760
TEST_SECTION_FAIL("build", "ptr_arith.o", "xdp")
// expected failure: check exit 1: 0,0.000999423,6240
TEST_SECTION_FAIL("build", "queue_stack.o", ".text")
// expected failure: check exit 1: 0,0.00099032,6240
TEST_SECTION_FAIL("build", "ringbuf_in_map.o", ".text")
// expected failure: check exit 1: 0,0.000259753,5600
TEST_SECTION_FAIL("build", "ringbuf_uninit.o", ".text")
TEST_SECTION("build", "sockmap.o", "sk_skb/stream_verdict")
TEST_SECTION("build", "stackok.o", ".text")
TEST_SECTION("build", "store_map_value_in_map.o", ".text")
TEST_SECTION("build", "tail_call.o", "xdp_prog")
TEST_SECTION("build", "tail_call.o", "xdp_prog/0")
// expected failure: check exit 1: 0,0.000208416,5600
TEST_SECTION_FAIL("build", "tail_call_bad.o", "xdp_prog")
TEST_SECTION("build", "tail_call_bad.o", "xdp_prog/0")
TEST_SECTION("build", "twomaps.o", ".text")
TEST_SECTION("build", "twomaps_btf.o", ".text")
TEST_SECTION("build", "twostackvars.o", ".text")
TEST_SECTION("build", "twotypes.o", ".text")
// expected failure: check exit 1: error: rejected: helper function is unavailable on this platform (at 7)
TEST_SECTION_FAIL("build", "wronghelper.o", "xdp")
