// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'cilium-ebpf'.
TEST_SECTION("cilium-ebpf", "btf_map_init-el.elf", "socket/main")
TEST_SECTION("cilium-ebpf", "btf_map_init-el.elf", "socket/tail")
TEST_SECTION("cilium-ebpf", "constants-el.elf", "sk_lookup/")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc
TEST_PROGRAM_SKIP("cilium-ebpf", "errors-el.elf", "socket", "poisoned_double", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc
TEST_PROGRAM_SKIP("cilium-ebpf", "errors-el.elf", "socket", "poisoned_kfunc", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc
TEST_PROGRAM_SKIP("cilium-ebpf", "errors-el.elf", "socket", "poisoned_single", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: invalid_kfunc")
TEST_SECTION("cilium-ebpf", "fentry_fexit-el.elf", "fentry/target")
TEST_SECTION("cilium-ebpf", "fentry_fexit-el.elf", "fexit/target")
TEST_SECTION("cilium-ebpf", "fentry_fexit-el.elf", "tc")
TEST_SECTION("cilium-ebpf", "freplace-el.elf", ".text")
TEST_SECTION("cilium-ebpf", "freplace-el.elf", "freplace/subprog")
TEST_SECTION("cilium-ebpf", "freplace-el.elf", "raw_tracepoint/sched_process_exec")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: fwd
TEST_SECTION_SKIP("cilium-ebpf", "fwd_decl-el.elf", "socket", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: fwd")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_kfunc_call_test_mem_len_pass1
TEST_SECTION_SKIP("cilium-ebpf", "invalid-kfunc-el.elf", "tc", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_kfunc_call_test_mem_len_pass1")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 6: Invalid type (r1.type == map_fd)
TEST_SECTION_FAIL("cilium-ebpf", "invalid_map_static-el.elf", "xdp", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 6: Invalid type (r1.type == map_fd)")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "kconfig-el.elf", "socket", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_fentry_test1
TEST_SECTION_SKIP("cilium-ebpf", "kfunc-el.elf", "fentry/bpf_fentry_test2", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_fentry_test1")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_skb_ct_lookup
TEST_SECTION_SKIP("cilium-ebpf", "kfunc-el.elf", "tc", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_skb_ct_lookup")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_PROGRAM_SKIP("cilium-ebpf", "kfunc-el.elf", "tp_btf/task_newtask", "call_weak_kfunc", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_PROGRAM_SKIP("cilium-ebpf", "kfunc-el.elf", "tp_btf/task_newtask", "weak_kfunc_missing", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_testmod_test_mod_kfunc
TEST_SECTION_SKIP("cilium-ebpf", "kfunc-kmod-el.elf", "tc", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: bpf_testmod_test_mod_kfunc")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_PROGRAM_SKIP("cilium-ebpf", "ksym-el.elf", "socket", "ksym_missing_test", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_PROGRAM_SKIP("cilium-ebpf", "ksym-el.elf", "socket", "ksym_test", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", ".text", "l1", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", ".text", "l1_s", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", ".text", "l1_w", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", ".text", "l2", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", ".text", "ww", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", "socket", "entry_l1", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", "socket", "entry_l1_s", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", "socket", "entry_l1_w", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", "socket", "entry_l2", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
// skipped (ElfLegacyMapLayout): Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds
TEST_PROGRAM_SKIP("cilium-ebpf", "linked-el.elf", "socket", "entry_ww", verify_test::VerifyIssueKind::ElfLegacyMapLayout, "Known loader limitation: legacy map symbol layout is not fully supported. Diagnostic: Legacy map symbol 'map_legacy_l2_s' has invalid offset: not aligned to 40-byte boundary or out of section bounds")
TEST_PROGRAM("cilium-ebpf", "linked1-el.elf", ".text", "l1", 4)
TEST_PROGRAM("cilium-ebpf", "linked1-el.elf", ".text", "l1_s", 4)
TEST_PROGRAM("cilium-ebpf", "linked1-el.elf", ".text", "l1_w", 4)
TEST_PROGRAM("cilium-ebpf", "linked1-el.elf", ".text", "ww", 4)
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2
TEST_PROGRAM_SKIP("cilium-ebpf", "linked1-el.elf", "socket", "entry_l1_s", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2
TEST_PROGRAM_SKIP("cilium-ebpf", "linked1-el.elf", "socket", "entry_l1_w", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2
TEST_PROGRAM_SKIP("cilium-ebpf", "linked1-el.elf", "socket", "entry_l2", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2
TEST_PROGRAM_SKIP("cilium-ebpf", "linked1-el.elf", "socket", "entry_ww", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l2")
TEST_PROGRAM("cilium-ebpf", "linked2-el.elf", ".text", "l1_s", 4)
TEST_PROGRAM("cilium-ebpf", "linked2-el.elf", ".text", "l1_w", 4)
TEST_PROGRAM("cilium-ebpf", "linked2-el.elf", ".text", "l2", 4)
TEST_PROGRAM("cilium-ebpf", "linked2-el.elf", ".text", "ww", 4)
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1
TEST_PROGRAM_SKIP("cilium-ebpf", "linked2-el.elf", "socket", "entry_l1", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1
TEST_PROGRAM_SKIP("cilium-ebpf", "linked2-el.elf", "socket", "entry_l1_s", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1
TEST_PROGRAM_SKIP("cilium-ebpf", "linked2-el.elf", "socket", "entry_l1_w", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1")
// skipped (ElfSubprogramResolution): Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1
TEST_PROGRAM_SKIP("cilium-ebpf", "linked2-el.elf", "socket", "entry_ww", verify_test::VerifyIssueKind::ElfSubprogramResolution, "Known loader limitation: subprogram resolution/disambiguation is incomplete for this object. Diagnostic: Subprogram not found: l1")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-14-el.elf", ".text", "global_fn", 2, verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-14-el.elf", ".text", "global_fn2", 2, verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-14-el.elf", "other", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
TEST_SECTION("cilium-ebpf", "loader-clang-14-el.elf", "socket")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-14-el.elf", "socket/2", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
TEST_SECTION("cilium-ebpf", "loader-clang-14-el.elf", "socket/3")
TEST_SECTION("cilium-ebpf", "loader-clang-14-el.elf", "socket/4")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-14-el.elf", "static", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-14-el.elf", "xdp", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-17-el.elf", ".text", "global_fn", 2, verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-17-el.elf", ".text", "global_fn2", 2, verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-17-el.elf", "other", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
TEST_SECTION("cilium-ebpf", "loader-clang-17-el.elf", "socket")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-17-el.elf", "socket/2", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
TEST_SECTION("cilium-ebpf", "loader-clang-17-el.elf", "socket/3")
TEST_SECTION("cilium-ebpf", "loader-clang-17-el.elf", "socket/4")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-17-el.elf", "static", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-17-el.elf", "xdp", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-20-el.elf", ".text", "global_fn", 2, verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-clang-20-el.elf", ".text", "global_fn2", 2, verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-20-el.elf", "other", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
TEST_SECTION("cilium-ebpf", "loader-clang-20-el.elf", "socket")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-20-el.elf", "socket/2", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
TEST_SECTION("cilium-ebpf", "loader-clang-20-el.elf", "socket/3")
TEST_SECTION("cilium-ebpf", "loader-clang-20-el.elf", "socket/4")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-clang-20-el.elf", "static", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-clang-20-el.elf", "xdp", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-el.elf", ".text", "global_fn", 2, verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_PROGRAM_FAIL("cilium-ebpf", "loader-el.elf", ".text", "global_fn2", 2, verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-el.elf", "other", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
TEST_SECTION("cilium-ebpf", "loader-el.elf", "socket")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-el.elf", "socket/2", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
TEST_SECTION("cilium-ebpf", "loader-el.elf", "socket/3")
TEST_SECTION("cilium-ebpf", "loader-el.elf", "socket/4")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader-el.elf", "static", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader-el.elf", "xdp", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion
TEST_PROGRAM_FAIL("cilium-ebpf", "loader_nobtf-el.elf", ".text", "global_fn", 2, verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 1: illegal recursion")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_PROGRAM_FAIL("cilium-ebpf", "loader_nobtf-el.elf", ".text", "global_fn2", 2, verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader_nobtf-el.elf", "other", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
TEST_SECTION("cilium-ebpf", "loader_nobtf-el.elf", "socket")
// skipped (ExternalSymbolResolution): Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.
TEST_SECTION_SKIP("cilium-ebpf", "loader_nobtf-el.elf", "socket/2", verify_test::VerifyIssueKind::ExternalSymbolResolution, "Known architectural limitation: unresolved external symbols are not modeled in offline verification. Diagnostic: Unresolved symbols found.")
TEST_SECTION("cilium-ebpf", "loader_nobtf-el.elf", "socket/3")
TEST_SECTION("cilium-ebpf", "loader_nobtf-el.elf", "socket/4")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)
TEST_SECTION_FAIL("cilium-ebpf", "loader_nobtf-el.elf", "static", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 2: Invalid type (r0.type == number)")
// expected failure (VerifierRecursionModeling): Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 18: illegal recursion
TEST_SECTION_FAIL("cilium-ebpf", "loader_nobtf-el.elf", "xdp", verify_test::VerifyIssueKind::VerifierRecursionModeling, "Known verifier limitation: subprogram call-graph handling rejects this recursion-shaped pattern. Diagnostic: error: 18: illegal recursion")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea0")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea1")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea10")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea11")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea12")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea13")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea14")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea15")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea16")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea17")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea18")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea19")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea2")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea20")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea21")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea22")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea23")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea24")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea25")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea26")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea27")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea28")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea29")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea3")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea4")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea5")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea6")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea7")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea8")
TEST_SECTION("cilium-ebpf", "manyprogs-el.elf", "kprobe/sys_execvea9")
TEST_SECTION("cilium-ebpf", "raw_tracepoint-el.elf", "raw_tracepoint/sched_process_exec")
TEST_SECTION("cilium-ebpf", "strings-el.elf", "xdp")
TEST_SECTION("cilium-ebpf", "struct_ops-el.elf", "struct_ops/test_1")
TEST_SECTION("cilium-ebpf", "subprog_reloc-el.elf", ".text")
// expected failure (VerifierTypeTracking): Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 19: Invalid type (r2.type == func)
TEST_SECTION_FAIL("cilium-ebpf", "subprog_reloc-el.elf", "xdp", verify_test::VerifyIssueKind::VerifierTypeTracking, "Known verifier limitation: register type refinement is too imprecise in this control-flow pattern. Diagnostic: 19: Invalid type (r2.type == func)")
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "add_atomic", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "check_array", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "check_struct", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "check_struct_pad", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "get_bss", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "get_data", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "get_rodata", 8)
TEST_PROGRAM("cilium-ebpf", "variables-el.elf", "socket", "set_vars", 8)
