// Copyright (c) Prevail Verifier contributors.
// SPDX-License-Identifier: MIT

#include "test_verify.hpp"

// Generated by scripts/generate_verify_project_tests.py for project 'build'.
TEST_SECTION_REJECT("build", "badrelo.o", ".text")
TEST_SECTION("build", "bounded_loop.o", "test")
TEST_PROGRAM("build", "bpf2bpf.o", ".text", "add1", 2)
TEST_PROGRAM("build", "bpf2bpf.o", ".text", "add2", 2)
TEST_SECTION("build", "bpf2bpf.o", "test")
TEST_SECTION("build", "byteswap.o", ".text")
TEST_SECTION("build", "cpumap.o", "xdp")
TEST_SECTION("build", "devmap.o", "xdp")
TEST_SECTION("build", "divzero.o", "test")
TEST_SECTION("build", "externalfunction.o", ".text")
TEST_SECTION("build", "global_func.o", "xdp")
TEST_SECTION("build", "global_variable.o", ".text")
TEST_SECTION("build", "global_variable_2.o", ".text")
TEST_SECTION("build", "hash_of_maps.o", ".text")
TEST_SECTION("build", "infinite_loop.o", "test")
TEST_SECTION("build", "lpm_trie.o", "xdp")
TEST_SECTION("build", "map_in_map.o", ".text")
TEST_SECTION("build", "map_in_map_anonymous.o", ".text")
TEST_SECTION("build", "map_in_map_legacy.o", ".text")
TEST_SECTION("build", "map_in_map_typedef.o", ".text")
TEST_SECTION("build", "mapoverflow.o", ".text")
TEST_SECTION("build", "mapunderflow.o", ".text")
TEST_SECTION("build", "packet_access.o", "xdp")
TEST_SECTION("build", "packet_start_ok.o", "xdp")
TEST_SECTION("build", "percpu_array.o", "xdp")
TEST_SECTION("build", "percpu_hash.o", "xdp")
TEST_PROGRAM("build", "prog_array.o", ".text", "func", 5)
TEST_PROGRAM("build", "prog_array.o", ".text", "func0", 5)
TEST_PROGRAM("build", "prog_array.o", ".text", "func1", 5)
TEST_PROGRAM("build", "prog_array.o", ".text", "func2", 5)
TEST_PROGRAM("build", "prog_array.o", ".text", "func3", 5)
TEST_SECTION("build", "sockmap.o", "sk_skb/stream_verdict")
TEST_SECTION("build", "stackok.o", ".text")
TEST_SECTION("build", "store_map_value_in_map.o", ".text")
TEST_SECTION("build", "tail_call.o", "xdp_prog")
TEST_SECTION("build", "tail_call.o", "xdp_prog/0")
TEST_SECTION("build", "tail_call_bad.o", "xdp_prog/0")
TEST_SECTION("build", "twomaps.o", ".text")
TEST_SECTION("build", "twomaps_btf.o", ".text")
TEST_SECTION("build", "twostackvars.o", ".text")
TEST_SECTION("build", "twotypes.o", ".text")
TEST_SECTION_REJECT("build", "wronghelper.o", "xdp")

// VerifierTypeTracking:
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "badmapptr.o", "test", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "bpf_loop_helper.o", "xdp", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "correlated_branch.o", "xdp", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_PROGRAM_FAIL("build", "global_func.o", ".text", "add_and_store", 2,
                  verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "packet_reallocate.o", "socket_filter", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "queue_stack.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "ringbuf_in_map.o", ".text", verify_test::VerifyIssueKind::VerifierTypeTracking)
// register type refinement is too imprecise in this control-flow pattern
TEST_SECTION_FAIL("build", "tail_call_bad.o", "xdp_prog", verify_test::VerifyIssueKind::VerifierTypeTracking)

// VerifierBoundsTracking:
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "badhelpercall.o", ".text", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "dependent_read.o", "xdp", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "invalid_map_access.o", ".text", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "loop.o", "test_md", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "mapvalue-overrun.o", ".text", verify_test::VerifyIssueKind::VerifierBoundsTracking)
// interval/bounds refinement loses precision for this memory-access proof
TEST_SECTION_FAIL("build", "packet_overflow.o", "xdp", verify_test::VerifyIssueKind::VerifierBoundsTracking)

// VerifierStackInitialization:
// stack initialization tracking is too coarse for this access path
TEST_SECTION_FAIL("build", "correlated_branch2.o", "socket_filter",
                  verify_test::VerifyIssueKind::VerifierStackInitialization)
// stack initialization tracking is too coarse for this access path
TEST_SECTION_FAIL("build", "perf_event_array.o", "xdp", verify_test::VerifyIssueKind::VerifierStackInitialization)
// stack initialization tracking is too coarse for this access path
TEST_SECTION_FAIL("build", "ringbuf_uninit.o", ".text", verify_test::VerifyIssueKind::VerifierStackInitialization)

// VerifierPointerArithmetic:
// pointer-arithmetic typing is too restrictive in this pattern
TEST_SECTION_FAIL("build", "ptr_arith.o", "xdp", verify_test::VerifyIssueKind::VerifierPointerArithmetic)

// VerifierMapTyping:
// map value/key typing and scalarization are too conservative here
TEST_SECTION_FAIL("build", "bpf_loop_helper.o", ".text", verify_test::VerifyIssueKind::VerifierMapTyping)
// map value/key typing and scalarization are too conservative here
TEST_SECTION_FAIL("build", "exposeptr.o", ".text", verify_test::VerifyIssueKind::VerifierMapTyping)
// map value/key typing and scalarization are too conservative here
TEST_SECTION_FAIL("build", "exposeptr2.o", ".text", verify_test::VerifyIssueKind::VerifierMapTyping)
// map value/key typing and scalarization are too conservative here
TEST_PROGRAM_FAIL("build", "global_func.o", ".text", "process_entry", 2,
                  verify_test::VerifyIssueKind::VerifierMapTyping)

// VerifierNullability:
// nullability tracking is too conservative on this path
TEST_SECTION_FAIL("build", "nullmapref.o", "test", verify_test::VerifyIssueKind::VerifierNullability)

// VerifierContextModeling:
// context-offset modeling is too restrictive for this access pattern
TEST_SECTION_FAIL("build", "ctxoffset.o", "sockops", verify_test::VerifyIssueKind::VerifierContextModeling)
